server:
  servlet:
    encoding:
      force-response: true
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect